Update patch set 4
Patch Set 4:

Note this won't compile with the latest updates to libwebm:

webm_file.cc: In member function ‘bool webm_dash::WebMFile::CuesFirstInCluster() const’:

webm_file.cc:342: error: no matching function for call to ‘mkvparser::Cluster::GetFirst() const’

../../libwebm/mkvparser.hpp:686: note: candidates are: long int mkvparser::Cluster::GetFirst(const mkvparser::BlockEntry*&) const

Patch-set: 4
Label: Code-Review=0
Label: Verified=0